-- ==========================================
-- PKOS Database Baseline
-- Version: V1
-- PostgreSQL 18
-- ==========================================

CREATE EXTENSION IF NOT EXISTS vector;

-- =====================================================
-- USERS
-- =====================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- =====================================================
-- NOTEBOOKS
-- =====================================================

CREATE TABLE notebooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notebooks_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_notebook_name_user
        UNIQUE (name, user_id)
);

CREATE INDEX idx_notebooks_user
    ON notebooks(user_id);

-- =====================================================
-- TAGS
-- =====================================================

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tags_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_tag_name_user
        UNIQUE (name, user_id)
);

CREATE INDEX idx_tags_user
    ON tags(user_id);

-- =====================================================
-- NOTES
-- =====================================================

    CREATE TABLE notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(200) NOT NULL,
        content TEXT NOT NULL,
        color VARCHAR(20),
        pinned BOOLEAN NOT NULL DEFAULT FALSE,
        archived BOOLEAN NOT NULL DEFAULT FALSE,
        deleted BOOLEAN NOT NULL DEFAULT FALSE,
        deleted_at TIMESTAMP,
        user_id BIGINT NOT NULL,
        notebook_id BIGINT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT fk_notes_user
            FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,

        CONSTRAINT fk_notes_notebook
            FOREIGN KEY (notebook_id)
            REFERENCES notebooks(id)
            ON DELETE RESTRICT
    );

CREATE INDEX idx_notes_user
    ON notes(user_id);

CREATE INDEX idx_notes_notebook
    ON notes(notebook_id);

CREATE INDEX idx_notes_user_deleted
    ON notes(user_id, deleted);

CREATE INDEX idx_notes_user_archived
    ON notes(user_id, archived);

-- =====================================================
-- NOTE_TAGS
-- =====================================================

CREATE TABLE note_tags (
    note_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    CONSTRAINT pk_note_tags
        PRIMARY KEY (note_id, tag_id),

    CONSTRAINT fk_note_tags_note
        FOREIGN KEY (note_id)
        REFERENCES notes(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_note_tags_tag
        FOREIGN KEY (tag_id)
        REFERENCES tags(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_note_tags_tag
    ON note_tags(tag_id);

-- =====================================================
-- FILES
-- =====================================================

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_files_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_files_user
    ON files(user_id);

-- =====================================================
-- FILE_CONTENTS
-- =====================================================

CREATE TABLE file_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    extraction_type VARCHAR(50) NOT NULL,
    file_metadata_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_file_contents_file
        FOREIGN KEY (file_metadata_id)
        REFERENCES files(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_file_contents_extraction_type
    ON file_contents(extraction_type);


-- =====================================================
-- CONVERSATIONS
-- =====================================================

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_conversations_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_conversations_user
    ON conversations(user_id);

-- =====================================================
-- CONVERSATION_MESSAGES
-- =====================================================

CREATE TABLE conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    conversation_id BIGINT NOT NULL,

    CONSTRAINT fk_conversation_messages_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversations(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_conversation_messages_conversation
    ON conversation_messages(conversation_id);

CREATE INDEX idx_conversation_messages_created_at
    ON conversation_messages(created_at);

-- =====================================================
-- CONVERSATION_SUMMARIES
-- =====================================================

CREATE TABLE conversation_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary TEXT NOT NULL,
    summarized_message_count INTEGER NOT NULL,
    memory_processed_message_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    conversation_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_conversation_summaries_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversations(id)
        ON DELETE CASCADE
);


-- =====================================================
-- EVENTS
-- =====================================================

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    all_day BOOLEAN NOT NULL DEFAULT FALSE,
    location VARCHAR(255),
    color VARCHAR(20),
    remind_at TIMESTAMP,
    reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_events_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_events_user
    ON events(user_id);

CREATE INDEX idx_events_start_time
    ON events(start_time);

-- =====================================================
-- REMINDERS
-- =====================================================

CREATE TABLE reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remind_at TIMESTAMP NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    notified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note_id BIGINT UNIQUE,
    event_id BIGINT UNIQUE,

    CONSTRAINT fk_reminders_note
        FOREIGN KEY (note_id)
        REFERENCES notes(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reminders_event
        FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);


-- =====================================================
-- MEMORIES
-- =====================================================

CREATE TABLE memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    memory_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CURRENT',
    source VARCHAR(30) NOT NULL,
    value VARCHAR(500) NOT NULL,
    normalized_value VARCHAR(500) NOT NULL,
    confidence NUMERIC(3,2) NOT NULL,
    observation_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_memories_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_memory_user_type_value
        UNIQUE (user_id, memory_type, value)
);

CREATE INDEX idx_memory_user
    ON memories(user_id);

CREATE INDEX idx_memory_type
    ON memories(memory_type);

-- =====================================================
-- MEMORY_EMBEDDINGS
-- =====================================================

CREATE TABLE memory_embeddings (
    memory_id BIGINT PRIMARY KEY,
    embedding vector(3072) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_memory_embeddings_memory
        FOREIGN KEY (memory_id)
        REFERENCES memories(id)
        ON DELETE CASCADE
);

-- =====================================================
-- NOTE_EMBEDDINGS
-- =====================================================

CREATE TABLE note_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL UNIQUE,
    embedding_model VARCHAR(100) NOT NULL,
    embedding_version INTEGER NOT NULL,
    embedding vector(3072) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_note_embeddings_note
        FOREIGN KEY (note_id)
        REFERENCES notes(id)
        ON DELETE CASCADE
);


-- =====================================================
-- AUDIT_LOGS
-- =====================================================

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- =====================================================
-- NOTIFICATIONS
-- =====================================================

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(500) NOT NULL,
    type VARCHAR(30) NOT NULL,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    reminder_id BIGINT,
    event_id BIGINT,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_notifications_reminder
        FOREIGN KEY (reminder_id)
        REFERENCES reminders(id),

    CONSTRAINT fk_notifications_event
        FOREIGN KEY (event_id)
        REFERENCES events(id)
);