spring.application.name=pkos-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pkos
spring.datasource.username=postgres
spring.datasource.password=pkos@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=PkosBackendSecretKeyForJwtAuthentication2026PkosSecretKey
jwt.expiration=86400000
