# =========================
# Database
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# =========================
# Logging
# =========================
logging.level.root=WARN
logging.level.com.pkos.backend=INFO